### PR TITLE
Permit logged-in users to query for media

### LINKED ISSUE #1959: GET request for media files results in an empty array
Hi

I have been trying to fetch all the media files from the REST API using restangular, but no matter how I try it fails, so I decided to test the media endpoint via PostMan app and realized that although I can see the media files json object in my browsers when I browse to /wp-json/wp/v2/media but using PostMan or using restangular it always results in an empty array.

The funny part is that during the time I was pulling my hair for getting the media files, the files showed up only once, and after one refresh they were gone forever, this could be a bug in the wp rest plugin.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #1959

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@WP-API/amigos #reviewmerge

File: lib/endpoints/class-wp-rest-posts-controller.php [hunk 1]
```diff
@@ -1604,7 +1604,7 @@ public function get_collection_params() {
 			),
 		);
 		$params['status'] = array(
-			'default'           => 'publish',
+			'default'           => 'attachment' === $this->post_type ? 'inherit' : 'publish',
```
Comment (joehoyle) [inline lib/endpoints/class-wp-rest-posts-controller.php]: If I do a request logged out for `/media` and there's a bunch of posts with `post_status=inherit` which are attached to private posts, what does the response look like? Does it just remove the attachments I can't view (thus I get 6 results rather than the default 10) or do I get an error, or somethign else?

Comment (danielbachhuber) [inline lib/endpoints/class-wp-rest-posts-controller.php]: > Does it just remove the attachments I can't view (thus I get 6 results rather than the default 10)

Yes, which is a consistent pattern we have throughout the controllers.

Comment (joehoyle) [inline lib/endpoints/class-wp-rest-posts-controller.php]: :+1:
