### PR TITLE
Fix post taxonomy terms link urls

### LINKED ISSUE #1383: Getting terms by post id doesn't work
When calling, `wp/v2/posts/1` (for instance), the following links are returned in the JSON response:

    "_links": {
        "http://v2.wp-api.org/term": [
            {
                "embeddable": true, 
                "href": "http://.../wp/v2/terms/category?post=1", 
                "taxonomy": "category"
            }, 
           // ...
        ]
    }

But when calling `wp/v2/terms/category?post=1`, all the available categories are returned instead of just the ones of post of id `1` in this example.

### PR DESCRIPTION
**Pull request by rachelbaker**
Fixes #1383

This was missed in #1216, where the routes for the Taxonomies and Terms for a Post moved.

### CODE REVIEW

**Comment by rachelbaker** [comment]
@WP-API/amigos #reviewmerge

File: lib/endpoints/class-wp-rest-posts-controller.php [hunk 1]
```diff
@@ -1155,13 +1155,11 @@ protected function prepare_links( $post ) {
 				}
 
 				if ( 'post_tag' === $tax ) {
```
Comment (joehoyle) [inline lib/endpoints/class-wp-rest-posts-controller.php]: We should remove this special case, I can pick up if you want @rachelbaker

Comment (rachelbaker) [inline lib/endpoints/class-wp-rest-posts-controller.php]: @joehoyle thank you, please do.

**Comment by rachelbaker** [comment]
Merged #1447

File: lib/endpoints/class-wp-rest-posts-controller.php [hunk 2]
```diff
@@ -1154,13 +1154,8 @@ protected function prepare_links( $post ) {
 					continue;
 				}
 
-				if ( 'post_tag' === $tax ) {
```
Comment (jdolan) [inline lib/endpoints/class-wp-rest-posts-controller.php]: Is there going to be some alignment on "tag" (`rest_base`) vs "post_tag" (`slug`)? I get that "post_tag" is "ugly," but who really cares? The API should be data-driven, and not make special cases for personal preferences. The more the API special-cases "tag", the less consistent it becomes. Please, I beg you, use `$tax->slug` everywhere.

Comment (joehoyle) [inline lib/endpoints/class-wp-rest-posts-controller.php]: @jdolan this issue is about using the rest base, so your concern is not specifically here. However, as far as the API exposes data, you'll only ever see `tag`, not a mix - so I don't know why it's a big issue. Tags are not just for posts, so the name is confusing, that's my 2c anyway. This change just fixes one small inconsistency where we didn't use `rest_base` (where we always should be doing).

Comment (jdolan) [inline lib/endpoints/class-wp-rest-posts-controller.php]: It's an issue because `rest_base` is never exposed to the client. Nowhere in the JSON response for the taxonomy object does it include `rest_base`. It does, however, include the `slug` -- and `slug` is precisely what should be used to map to URIs. That's _what slug is for_. See #1381.

Comment (joehoyle) [inline lib/endpoints/class-wp-rest-posts-controller.php]: @jdolan #1381 still stands, that's not about what this fix was for. This is about using rest_base to build the url. If #1381 means we set `rest_base` to be `post_tag` then fine. This code is right either way.

Comment (jdolan) [inline lib/endpoints/class-wp-rest-posts-controller.php]: I realize that. I just see more special casing to accommodate the `rest_base` mistake seeping into the code and it makes me cringe. This code doesn't even use `rest_base` from a constant or some other variable -- it just replicates it. If I'm a jerk for pointing this out, then I apologize.

Comment (joehoyle) [inline lib/endpoints/class-wp-rest-posts-controller.php]: @jdolan `rest_base` is not about `post_tag` we have to support it for custom taxonomies too. If anything, this commit supports you argument, it is _getting rid_ of special casing the case.
