### PR TITLE
Use wrapper for `sanitize_title` to avoid messed up slugs.

### LINKED ISSUE #2487: Accented characters passed for slug are not removed
I noticed that passing a `slug` string with accented characters to the `POST|PUT /wp/v2/posts` endpoints does not result in expected behavior:

Request:

``` bash
curl -i --user admin:password \
    -H "Content-Type: application/json; charset=UTF-8" \
    -X POST \
    -d '
{
  "title": "Tęst Acceńted Chäræcters",
  "slug": "tęst-acceńted-chäræcters",
  "status": "publish"
}' \
    http://local.wordpress.dev/wp-json/wp/v2/posts
```

Abbreviated response:

``` json
{
  "guid": {
    "rendered": "http://local.wordpress.dev/2016/05/09/t%c4%99st-acce%c5%84ted-ch%c3%a4r%c3%a6cters/",
    "raw": "http://local.wordpress.dev/2016/05/09/t%c4%99st-acce%c5%84ted-ch%c3%a4r%c3%a6cters/"
  },
  "slug": "t%c4%99st-acce%c5%84ted-ch%c3%a4r%c3%a6cters",
  "link": "http://local.wordpress.dev/2016/05/09/t%c4%99st-acce%c5%84ted-ch%c3%a4r%c3%a6cters/",
  "title": {
    "raw": "Tęst Acceńted Chäræcters",
    "rendered": "Tęst Acceńted Chäræcters"
  }
}
```

Root cause is something that's been discussed in different forms (#1712, #1520, https://core.trac.wordpress.org/ticket/34659) -- passing unexpected arguments to core sanitization functions via the schema's `sanitize_callback` arg. `sanitize_title` expects a fallback title and context as it's second and third arguments, not a `WP_REST_Request` instance and parameter name. The latter is interfering with the default `save` context which is what creates the problem.

### PR DESCRIPTION
**Pull request by joehoyle**
This is required sinse passing sanitize_title directly will result in
messed up slugs due to the `context` param getting a garbage value.

Fixes #2487

### CODE REVIEW

**Comment by rmccue** [comment]
Duplicate of #1712; should bring over the changes from there.

File: lib/endpoints/class-wp-rest-posts-controller.php [hunk 1]
```diff
@@ -1798,4 +1798,16 @@ public function validate_user_can_query_private_statuses( $value, $request, $par
...
+	/**
+	 * Sanitize a post's title.
+	 *
+	 * It's not possible to pass `sanitize_title` directly as the sanitize_callback
+	 * as that will cause 3 params inadvertantly being passed to `sanitize_title`.
+	 *
+	 * @param string $slug
+	 * @return string
+	 */
+	public function sanitize_slug( $slug ) {
```
Comment (danielbachhuber) [inline lib/endpoints/class-wp-rest-posts-controller.php]: This is going into core?

Comment (rmccue) [reply lib/endpoints/class-wp-rest-posts-controller.php]: Until the proper fix in https://core.trac.wordpress.org/ticket/34659 goes in, we still need to work around the bug.

Comment (danielbachhuber) [reply lib/endpoints/class-wp-rest-posts-controller.php]: Ok. Could we add a note on the method then?

**Comment by rmccue** [comment]
Updated with notes as above; @joehoyle happy with this?

**Comment by joehoyle** [comment]
Looks good to me

**Review by rmccue — APPROVED** [review]

File: tests/test-rest-posts-controller.php [hunk 2]
```diff
@@ -1360,6 +1360,22 @@ public function test_update_post_slug() {
...
+		$params = $this->set_post_data( array(
+			'slug' => 'tęst-acceńted-chäræcters',
+		) );
+		$request->set_body_params( $params );
+		$response = $this->server->dispatch( $request );
+
+		$new_data = $response->get_data();
+		$this->assertEquals( 'test-accented-charaecters', $new_data['slug'] );
+		$post = get_post( $new_data['id'] );
+		$this->assertEquals( 'test-accented-charaecters', $post->post_name );
```
Comment (kadamwhite) [inline tests/test-rest-posts-controller.php:1376]: Typo here

**Comment by kadamwhite** [comment]
Wait no. D'oh :)
